### ISSUE TITLE
Can not select the option in <select> tag.

### ISSUE THREAD

**Issue by kmvan** [redgeoff/paste-image#32]
When click the <select>, <option> will hide so fast XD.

**Comment by Lenny4** [comment]
Comment (l:160): 
/*document.addEventListener("click", function () {
                    e._pasteCatcherFocus()
                })*/
And (l164):
/*, this._pasteCatcher.focus()*/

**Comment by Lenny4** [comment]
@kmvan

**Comment by kmvan** [comment]
OMG, 2 years reply. Thank you.
